# Generated by Django 4.2.3 on 2024-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yonalish',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='rasm/'),
        ),
    ]
