# Generated by Django 4.2.3 on 2024-08-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0002_yonalish_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='yonalish',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='oquvchi.yonalish'),
            preserve_default=False,
        ),
    ]
