# Generated by Django 4.2.3 on 2024-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0003_kurs_yonalish'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='fayl_uy',
            field=models.FileField(blank=True, null=True, upload_to='darslik/'),
        ),
    ]
